name: Build kind node image

on:
  workflow_dispatch:
    # Enable manual trigger of this action.
    inputs:
      k8sGitBranch:
        description: k8s branch to build kind node image from
        default: "release-1.22"
        required: true
      k8sVersion:
        description: k8s version to build kind node image from
        default: "1.22.3"
        required: true
      imageRepo:
        description: Container image repo name to be used for the kind node image. New images are pushed to this repo when released
        default: "storageos/kind-node"
        required: true
      kindGitRepo:
        description: kind git repo to build kind from
        default: "github.com/kubernetes-sigs/kind"
        required: true
      kindGitBranch:
        description: kind git repo branch to build kind from
        default: "main"
        required: true

env:
  K8S_GIT_REPO_BRANCH: ${{ github.event.inputs.k8sGitBranch }}
  K8S_VERSION: ${{ github.event.inputs.k8sVersion }}
  KIND_NODE_IMAGE_REPO: ${{ github.event.inputs.imageRepo }}
  KIND_GIT_REPO: ${{ github.event.inputs.kindGitRepo }}
  KIND_GIT_REPO_BRANCH: ${{ github.event.inputs.kindGitBranch }}
  GOPATH: ${{ github.workspace }}/go
  
jobs:
  build-kind-node-image:
    runs-on: ubuntu-latest
    name: Build kind node image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Get K8S
        run: bash get-k8s.sh
      - name: Build node image
        run: bash node-build.sh
      - name: Test image
        run: bash run-kind.sh
      - name: Release node image
        run: bash release-image.sh
